### ISSUE TITLE
[NFR] Hell Let Loose

### ISSUE THREAD

**Issue by philj76** [GameTactic/Issues#14]
Could this be added to the available game options please?

**Comment by NikoGrano** [comment]
@philj76 Im sorry, but I need to close this due it wasn't added here by using template. Using template allows us to handle these requests on board and get automatically assigned correctly.

@bryansamuel1 FYI.

I'm creating new issue to replace this.

**Comment by NikoGrano** [comment]
@philj76 Please use template found [here](https://github.com/GameTactic/Issues/issues/new?assignees=&labels=gathering-interest%2C+nfr%2C+needs-contributor&template=feature-request.md&title=%5BNFR%5D).
