### ISSUE TITLE
Steam Login

### ISSUE THREAD

**Issue by philj76** [GameTactic/Issues#15]
Hello, sorry if I am not in the correct place or using the correct form for reporting an issue.
Please correct and direct me, if this is wrong.

I am not able to log into wottactic using my steam login. It takes me to the Steam login web page, but after confirming the login, it just hangs there.
Wargaming does work though.

**Comment by NikoGrano** [comment]
Investigating currently. Confirmed the issue and working on creating a hotfix.

**Comment by NikoGrano** [comment]
Fix applied and verified to be working :tada:!
