### ISSUE TITLE
Conquero Blades 

### ISSUE THREAD

**Issue by SOMvarox** [GameTactic/Issues#19]
somos una gran camunidad de muchas casas esperando si a ver nos facilitarais el acceso a estos mapas

**Comment by NikoGrano** [comment]
@SOMvarox Please use template found [here](https://github.com/GameTactic/Issues/issues/new?assignees=&labels=gathering-interest%2C+nfr%2C+needs-contributor&template=feature-request.md&title=%5BNFR%5D).

Please also be more specific.
