### ISSUE TITLE
[NFR] caliber

### ISSUE THREAD

**Issue by LeshaPotapenko** [GameTactic/Issues#20]
# Basics

- [ ] Needs maps to work.
- [ ] Needs entities to work.
- [ ] I am officer in a clan/community.
- [ ] I am member of GameTactic Discord.
- [ ] I am willing to contribute (Provide resources like maps, entities and keep the up-to-date).

# Technical questions

- **Q:** Is there API available for entities and maps? 
    - **A:** YOUR_ANSWER_HERE
- **Q:** How often is entities and maps changing?
    - **A:** YOUR_ANSWER_HERE
- **Q:** Would you be able to get more interest for this issue?
    - **A:** YOUR_ANSWER_HERE

# Comments

**Comment by NikoGrano** [comment]
@LeshaPotapenko Would you mind to answer questions or I'm forced to close this #invalid.

**Comment by NikoGrano** [comment]
Ill close this for now, due you dont have any previous activity in GitHub. Edit your post with requested information and Ill reopen this.
