### ISSUE TITLE
Support for Valorant

### ISSUE THREAD

**Issue by KulaGGin** [GameTactic/Issues#21]
Creating this issue to start gathering images of maps and icons.

**Comment by NikoGrano** [comment]
@KulaGGin Please use template found [here](https://github.com/GameTactic/Issues/issues/new?assignees=&labels=gathering-interest%2C+nfr%2C+needs-contributor&template=feature-request.md&title=%5BNFR%5D).

After this has been created we can check your eligibility for Game Manager role, meaning you can help us create required resources to add support.
