### ISSUE TITLE
heroes and generals

### ISSUE THREAD

**Issue by fduxyd** [GameTactic/Issues#40]
Hi everybody,in the game heroes and generals I changed low a minimum graphics in the program nvidia profile inspector But I can't join the battle, how to bypass protection...
Sorry, I'm writing through a translator

export file  nvidia inspector [https://cloud.mail.ru/public/rpLw/3M3tnVhC4](url)
loading problem [https://cloud.mail.ru/public/w4CQ/WtgrMrjVz](url)

**Comment by NikoGrano** [comment]
This is not a game support channel.
