### ISSUE TITLE
Conqueros Blade

### ISSUE THREAD

**Issue by vaksone** [GameTactic/Issues#48]
![mapa](https://github.com/GameTactic/Issues/assets/93797768/c6a8574b-6756-4ab5-931f-ca65ddbbad27)

I would need to be able to insert game maps and insert units to be able to make strategies.

These maps would be used by many clans in the game since there is nothing similar either inside or outside the game

**Comment by NikoGrano** [comment]
Dup of https://github.com/GameTactic/Issues/issues/22
