### ISSUE TITLE
[NFR] Stalker Online

### ISSUE THREAD

**Issue by predator440** [GameTactic/Issues#8]
# Basics

- [ ] Needs maps to work.
- [ ] Needs entities to work.
- [ ] I am officer in a clan/community.
- [ ] I am member of GameTactic Discord.
- [ ] I am willing to contribute (Provide resources like maps, entities and keep the up-to-date).

# Technical questions

- **Q:** Is there API available for entities and maps? 
    - **A:** 
- **Q:** How often is entities and maps changing?
    - **A:** 
- **Q:** Would you be able to get more interest for this issue?
    - **A:** 

# Comments

**Comment by NikoGrano** [comment]
@predator440 Would you mind update answers for given questions in your issue? Would help us a lot! Thanks.

**Comment by NikoGrano** [comment]
Closing as invalid. Please use template. We need community/you to contribute required information before putting this into backlog.
